////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool
////     Changes to this file will be lost if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;
//using Northwind.Core.Base;

//namespace Northwind.Core.Customer.Actions
//{

//    public class GetCustomers :  BizCustomer
//    {

//        public override T Execute<T>()
//        {
//            try
//            {
//                Customers = null; //DbManager.GetCustomers();
//                Rules.CheckCustomers(Customers);
//                return (T)Convert.ChangeType(Customers, typeof(T));
//            }
//            catch (Exception e)
//            {
//                HandleException(e);
//                throw;
//            }

//        }
//        public GetCustomers() : base()
//        {
//        }
//    }

//}