////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool
////     Changes to this file will be lost if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;
//using Northwind.Core.Base;

//namespace Northwind.Core.Customer.Actions
//{
//    public class GetCustomerSummary : BizCustomer
//    {
//        public string CustomerId
//        {
//            get;
//            set;
//        }

//        public GetCustomerSummary(string CustomerID) : base()
//        {
//            CustomerId = CustomerID;

//        }

//        public override T Execute<T>()
//        {
//            try
//            {
//                Rules.CheckCustomerId(this.CustomerId);
//                Customer = null;//DbManager.GetCustomerOrderProductSummary(this.CustomerId);
//                Rules.ChangePhoneIf030(Customer.Phone);
//                return (T)Convert.ChangeType(Customer, typeof(T));
//            }
//            catch (Exception e)
//            {
//                HandleException(e);
//                throw;
//            }

//        }

//    }
//}
