////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool
////     Changes to this file will be lost if the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;
//using Northwind.Core.Base;

//namespace Northwind.Core.Customer.Actions
//{

//    public class SaveCustomer : BizCustomer
//    {

//        public SaveCustomer(Core.Base.RequestBase Request) : base()
//        {
//            this.Request = Request;
//        }

//        public override T Execute<T>()
//        {
//            try
//            {
//                Validate();
//                Customer = null;// DbManager.SaveCustomer(Customer);
//                ValidateRespons();
//                return (T)Convert.ChangeType(Customer, typeof(T));
//            }
//            catch (Exception e)
//            {
//                HandleException(e);
//                throw;
//            }

//        }

//        private void  Validate()
//        {
//            Rules.CheckCustomer(Customer);
//        }
//        private void ValidateRespons()
//        {
//            Rules.ChangePhoneIf030(Customer.Phone);
//        }
//    }

//}