//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Northwind.Core.Base;
using Northwind.entities;

namespace Northwind.Core.Customer.Actions
{

    public class SaveCustomer : BizCustomer
    {

        public SaveCustomer() : base()
        {
            
        }

        public override U Execute<T,U>(T request)
        {
            try
            {
                var req = request as entities.SaveCustomerRequest;
                AddRequest<entities.Customer>(req.Customer); 
                Rules(CustomerRules.Check1);
                Rules(CustomerRules.Check2);
                Rules(CustomerRules.Check11);
                Rules(CustomerRules.Check12);
                var Customer = DbManager.SaveCustomer(req.Customer);
                AddRespons<entities.Customer>(Customer);
                Rules(CustomerRules.Check13);
                var Result = new CustomerResult();
                Result.Customer = Customer;
                Result.StatusObject = StatusObject;
                return (U)Convert.ChangeType(Result, typeof(U));
            }
            catch (Exception e)
            {
                HandleException(e);
                throw;
            }

        }

        private void Validate()
        {
           
        }
        private void ValidateRespons()
        {
           
        }
    }

}