//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Northwind.Core.Base;
using Northwind.entities;

namespace Northwind.Core.Customer.Actions
{

    public class SaveCustomer : BizCustomer
    {

        public SaveCustomer() : base()
        {
            this.Request = Request;
        }

        public override U Execute<T,U>(T request)
        {
            try
            {
                var req = request as entities.SaveCustomerRequest;
                var res = new entities.CustomerResult();
                res.Customer = DbManager.SaveCustomer(req.Customer);
                return (U)Convert.ChangeType(res, typeof(U));
            }
            catch (Exception e)
            {
                HandleException(e);
                throw;
            }

        }

        private void Validate()
        {
            Rules.CheckCustomer(Customer);
        }
        private void ValidateRespons()
        {
            Rules.ChangePhoneIf030(Customer.Phone);
        }
    }

}