//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public abstract class BussinessCustomer : ObjectBase
{
	public override RuleBase Rules
	{
		get;
		set;
	}

	public virtual NW_Customer Customer
	{
		get;
		set;
	}

	public virtual IEnumerable<NW_Customer> Customers
	{
		get;
		set;
	}

	public override T Execute<T>()
	{
		throw new System.NotImplementedException();
	}

}

