//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class GetCustomerById : BussinessCustomer
{
	public string CustomerId
	{
		get;
		set;
	}

	public GetCustomerById(string CustomerID)
	{
	}

	public override T Execute<T>()
	{
		throw new System.NotImplementedException();
	}

}

