//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public interface IBussinessObject 
{
	StatusObject StatusObject { get;set; }

	RuleBase Rules { get;set; }

	object Entity { get;set; }

	IEnumerable<object> Entities { get;set; }

	void Addrequest(object item);

	T Execute<T>();

}

