//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NW_Customer
{
	public virtual object CustomerID
	{
		get;
		set;
	}

	public virtual object CompanyName
	{
		get;
		set;
	}

	public virtual object ContactName
	{
		get;
		set;
	}

	public virtual object ContactTitle
	{
		get;
		set;
	}

	public virtual object Address
	{
		get;
		set;
	}

	public virtual object City
	{
		get;
		set;
	}

	public virtual object Region
	{
		get;
		set;
	}

	public virtual object PostalCode
	{
		get;
		set;
	}

	public virtual object Country
	{
		get;
		set;
	}

	public virtual object Phone
	{
		get;
		set;
	}

	public virtual object Fax
	{
		get;
		set;
	}

}

