//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class NWManager
{
	public static  NW_Customer GetCustomerSummary()
	{
        // IBussinessObject bizobj = new GetCustomerSummary(CustomerId);
        //return bizobj.Execute<NW_Customer>();
        return null;
    }

}

