//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class ResponsCustomer
{
	public virtual NW_Customer Customer
	{
		get;
		set;
	}

	public virtual StatusObject StatusObject
	{
		get;
		set;
	}

}

