//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class StatusObject
{
	public virtual string StackTrace
	{
		get;
		set;
	}

	public virtual string StatusText
	{
		get;
		set;
	}

	public virtual string Message
	{
		get;
		set;
	}

	public virtual Exception Exception
	{
		get;
		set;
	}

	private Status _Status
	{
		get;
		set;
	}

	private string _StackTrace
	{
		get;
		set;
	}

	public virtual bool Ok
	{
		get;
		set;
	}

	public virtual Status Status
	{
		get;
		set;
	}

	public virtual void RuleHit(string Message)
	{
		throw new System.NotImplementedException();
	}

	public virtual void Error(System.Exception e)
	{
		throw new System.NotImplementedException();
	}

}

