//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Northwind.Core.Common
{
    /// <remarks>Set to inherit from Exception</remarks>
    public class RuleException :Exception 
    {
       private string _Message;
        public override string Message { get { return _Message; } }

        public RuleException(string Message)
        {
            _Message = Message;
        }

    }

    public class InfoException : Exception
    {
        private string _Message;
        public override string Message { get { return _Message; } }

        public InfoException(string Message)
        {
            _Message = Message;
        }

    }

}