//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace Northwind.Core.Common
{

    public class StatusObject
    {
        public StatusObject()
        {
        }
        public virtual bool Ok
        {
            get;
            set;
        }

        private Status _Status
        {
            get;
            set;
        }

        private string _StackTrace
        {
            get;
            set;
        }

        public virtual Status Status
        {
            get { return _Status; }
            set
            {
                _Status = value;
                StatusText = _Status.ToString();
            }
        }
        public string StackTrace
        {
            get
            {
                if (string.IsNullOrEmpty(_StackTrace))
                {
                    return "";
                }
                return _StackTrace;
            }
            set
            {
                _StackTrace = value;
            }
        }

        public virtual string StatusText
        {
            get;
            set;
        }

        public virtual string Message
        {
            get;
            set;
        }

        public virtual Exception Exception
        {
            get;
            set;
        }

    }

}